#definir la imagen que 
FROM node:20-slim
#definir carpeta dentro del contenedor
WORKDIR /app
#copiar
COPY package*.json ./
#ejecutar
RUN npm install
#copiar el fuente
COPY . .
#exponer puerto
EXPOSE 3000
CMD [ "node","index.js" ]
 
